// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queryservice.proto

package queryservice;

public final class Queryservice {
  private Queryservice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022queryservice.proto\022\014queryservice\032\013quer" +
      "y.proto\032\020binlogdata.proto2\373\016\n\005Query\022:\n\007E" +
      "xecute\022\025.query.ExecuteRequest\032\026.query.Ex" +
      "ecuteResponse\"\000\022I\n\014ExecuteBatch\022\032.query." +
      "ExecuteBatchRequest\032\033.query.ExecuteBatch" +
      "Response\"\000\022N\n\rStreamExecute\022\033.query.Stre" +
      "amExecuteRequest\032\034.query.StreamExecuteRe" +
      "sponse\"\0000\001\0224\n\005Begin\022\023.query.BeginRequest" +
      "\032\024.query.BeginResponse\"\000\0227\n\006Commit\022\024.que" +
      "ry.CommitRequest\032\025.query.CommitResponse\"" +
      "\000\022=\n\010Rollback\022\026.query.RollbackRequest\032\027." +
      "query.RollbackResponse\"\000\022:\n\007Prepare\022\025.qu" +
      "ery.PrepareRequest\032\026.query.PrepareRespon" +
      "se\"\000\022O\n\016CommitPrepared\022\034.query.CommitPre" +
      "paredRequest\032\035.query.CommitPreparedRespo" +
      "nse\"\000\022U\n\020RollbackPrepared\022\036.query.Rollba" +
      "ckPreparedRequest\032\037.query.RollbackPrepar" +
      "edResponse\"\000\022X\n\021CreateTransaction\022\037.quer" +
      "y.CreateTransactionRequest\032 .query.Creat" +
      "eTransactionResponse\"\000\022F\n\013StartCommit\022\031." +
      "query.StartCommitRequest\032\032.query.StartCo" +
      "mmitResponse\"\000\022F\n\013SetRollback\022\031.query.Se" +
      "tRollbackRequest\032\032.query.SetRollbackResp" +
      "onse\"\000\022^\n\023ConcludeTransaction\022!.query.Co" +
      "ncludeTransactionRequest\032\".query.Conclud" +
      "eTransactionResponse\"\000\022R\n\017ReadTransactio" +
      "n\022\035.query.ReadTransactionRequest\032\036.query" +
      ".ReadTransactionResponse\"\000\022I\n\014BeginExecu" +
      "te\022\032.query.BeginExecuteRequest\032\033.query.B" +
      "eginExecuteResponse\"\000\022X\n\021BeginExecuteBat" +
      "ch\022\037.query.BeginExecuteBatchRequest\032 .qu" +
      "ery.BeginExecuteBatchResponse\"\000\022N\n\rMessa" +
      "geStream\022\033.query.MessageStreamRequest\032\034." +
      "query.MessageStreamResponse\"\0000\001\022C\n\nMessa" +
      "geAck\022\030.query.MessageAckRequest\032\031.query." +
      "MessageAckResponse\"\000\022O\n\016ReserveExecute\022\034" +
      ".query.ReserveExecuteRequest\032\035.query.Res" +
      "erveExecuteResponse\"\000\022^\n\023ReserveBeginExe" +
      "cute\022!.query.ReserveBeginExecuteRequest\032" +
      "\".query.ReserveBeginExecuteResponse\"\000\022:\n" +
      "\007Release\022\025.query.ReleaseRequest\032\026.query." +
      "ReleaseResponse\"\000\022K\n\014StreamHealth\022\032.quer" +
      "y.StreamHealthRequest\032\033.query.StreamHeal" +
      "thResponse\"\0000\001\022F\n\007VStream\022\032.binlogdata.V" +
      "StreamRequest\032\033.binlogdata.VStreamRespon" +
      "se\"\0000\001\022R\n\013VStreamRows\022\036.binlogdata.VStre" +
      "amRowsRequest\032\037.binlogdata.VStreamRowsRe" +
      "sponse\"\0000\001\022[\n\016VStreamResults\022!.binlogdat" +
      "a.VStreamResultsRequest\032\".binlogdata.VSt" +
      "reamResultsResponse\"\0000\001B+Z)vitess.io/vit" +
      "ess/go/vt/proto/queryserviceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.vitess.proto.Query.getDescriptor(),
          binlogdata.Binlogdata.getDescriptor(),
        }, assigner);
    io.vitess.proto.Query.getDescriptor();
    binlogdata.Binlogdata.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
