name: image_push

on: workflow_dispatch

jobs:
  push_to_docker_hub:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Clone vitess repository
        uses: actions/checkout@v2
        with:
          repository: vitessio/vitess
          path: src/test/resources/vitess_env/build_vitess/vitess
          ref: v13.0.0
      - name: run setup.sh v13.0.0
        run: cd src/test/resources/vitess_env && chmod ug+x setup.sh && ./setup.sh
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to Docker Hub
        run: docker push vtdriverio/vtdriver-env:latest
