# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  maven-test-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Test locally
        run: mvn clean test -Dtest=\
          com.jd.jdbc.cache.LRUCacheTest,\
          com.jd.jdbc.evalengine.ArithmeticTest,\
          com.jd.jdbc.planbuilder.PlanTest,\
          com.jd.jdbc.sqlparser.NormalizeRewritePutTest,\
          com.jd.jdbc.sqlparser.SmartNormalizeDateTest,\
          com.jd.jdbc.sqlparser.SmartNormalizeTest1,\
          com.jd.jdbc.sqlparser.SmartNormalizeTest2,\
          com.jd.jdbc.context.ContextTest,\
          com.jd.jdbc.sqltypes.VtValueTest,\
          com.jd.jdbc.topo.discovery.TestHealthCheck,\
          com.jd.jdbc.util.SplitMultiQueryUtilsTest
