# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  maven-test-job:
    runs-on: ubuntu-latest
    services:
      vitess1202:
        image: wanghy1995/vtdriver-env:latest
        options: >-
          --health-cmd "mysqladmin ping -h127.0.0.1 -P15306 -umysql_user -pmysql_password"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 50
          --health-start-period 150s
          -it
        ports:
          - 16100:16100
          - 16101:16101
          - 16102:16102
          - 16300:16300
          - 16301:16301
          - 16302:16302
          - 16400:16400
          - 16401:16401
          - 16402:16402
          - 15000:15000
          - 15001:15001
          - 15306:15306
          - 15100:15100
          - 15101:15101
          - 15102:15102
          - 15300:15300
          - 15301:15301
          - 15302:15302
          - 15400:15400
          - 15401:15401
          - 15402:15402
          - 2379:2379
          - 17100:17100
          - 17101:17101
          - 17102:17102
          - 17300:17300
          - 17301:17301
          - 17302:17302
          - 17400:17400
          - 17401:17401
          - 17402:17402
        env:
          HOST_IP: 127.0.0.1

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Test locally
        run: mvn clean test -Dtest=\
          com.jd.jdbc.cache.LRUCacheTest,\
          com.jd.jdbc.evalengine.ArithmeticTest,\
          com.jd.jdbc.planbuilder.PlanTest,\
          com.jd.jdbc.sqlparser.NormalizeRewritePutTest,\
          com.jd.jdbc.sqlparser.SmartNormalizeDateTest,\
          com.jd.jdbc.sqlparser.SmartNormalizeTest1,\
          com.jd.jdbc.sqlparser.SmartNormalizeTest2,\
          com.jd.jdbc.context.ContextTest,\
          com.jd.jdbc.sqltypes.VtValueTest,\
          com.jd.jdbc.topo.discovery.TestHealthCheck,\
          com.jd.jdbc.util.SplitMultiQueryUtilsTest
      - name: Test driver
        run: mvn clean test -Dtest=\
          com.jd.jdbc.concurrency.AllErrorRecorderTest,\
          com.jd.jdbc.engine.destination.DestinationTest,\
          com.jd.jdbc.engine.RouteEngineTest,\
          com.jd.jdbc.engine.DeleteEngineTest,\
          com.jd.jdbc.engine.InsertEngineTest,\
          com.jd.jdbc.engine.SelectEngineTest,\
          com.jd.jdbc.engine.UpdateEngineTest,\
          com.jd.jdbc.engine.join.ShardedJoinTest,\
          com.jd.jdbc.engine.join.UnShardedJoinTest,\
          com.jd.jdbc.engine.join.JoinTypeTest,\
          com.jd.jdbc.engine.subquery.ShardedSubqueryTest,\
          com.jd.jdbc.engine.subquery.UnShardedSubqueryTest,\
          com.jd.jdbc.engine.union.ShardedUnionTest,\
          com.jd.jdbc.engine.union.UnShardedUnionTest,\
          com.jd.jdbc.planbuilder.PlanCacheTest,\
          com.jd.jdbc.show.ShowVitessShardsTest,\
          com.jd.jdbc.sqlparser.ChangeSchemaTest,\
          com.jd.jdbc.vitess.TimeTest,\
          com.jd.jdbc.vitess.TransactionTest,\
          com.jd.jdbc.vitess.TypeTest,\
          com.jd.jdbc.vitess.VitessAutoGeneratedKeysTest,\
          com.jd.jdbc.vitess.VitessDriverConsolidatorTest,\
          com.jd.jdbc.vitess.VitessDriverDatabaseMetaDataTest,\
          com.jd.jdbc.vitess.VitessDriverFindColumnByName,\
          com.jd.jdbc.vitess.VitessDriverReadWriteSplit,\
          com.jd.jdbc.vitess.VitessDriverUnshardedTest,\
          com.jd.jdbc.vitess.allowMultiQueries.VitessDriverAllowMultiQuerieTest,\
          com.jd.jdbc.vitess.allowMultiQueries.VitessDriverMultiQuerySubsectionTest,\
          com.jd.jdbc.vitess.allowMultiQueries.VitessDriverMultiQueriesTest
      - name: Test split table
        run: mvn clean test -Dtest=\
          com.jd.jdbc.table.unshard.ConcurrentSplitTableUnshardTest,\
          com.jd.jdbc.table.unshard.LastInsertIdUnShardTest,\
          com.jd.jdbc.table.unshard.TableAutoGeneratedKeysUnShardTest,\
          com.jd.jdbc.table.unshard.TransactionUnShardTest,\
          com.jd.jdbc.table.engine.unshard.DeleteUnShardTest,\
          com.jd.jdbc.table.engine.unshard.InsertUnShardTest,\
          com.jd.jdbc.table.engine.unshard.SelectUnShardTest,\
          com.jd.jdbc.table.engine.unshard.UpdateUnShardTest,\
          com.jd.jdbc.table.ConcurrentSplitTableTest,\
          com.jd.jdbc.table.LastInsertIdTest,\
          com.jd.jdbc.table.engine.join.JoinTest,\
          com.jd.jdbc.table.engine.subquery.SubqueryTest,\
          com.jd.jdbc.table.engine.union.UnionTest,\
          com.jd.jdbc.table.engine.DeleteTest,\
          com.jd.jdbc.table.engine.InsertTest,\
          com.jd.jdbc.table.engine.SelectTest,\
          com.jd.jdbc.table.engine.UpdateTest,\
          com.jd.jdbc.table.TableAutoGeneratedKeysTest,\
          com.jd.jdbc.table.multiquery.MultiqueryTest,\
          com.jd.jdbc.table.streamquery.StreamQueryTest,\
          com.jd.jdbc.table.TransactionTest
      - name: Test timezone
        run: mvn clean test -Dtest=\
          com.jd.jdbc.vitess.TimeZoneTest,\
          com.jd.jdbc.vitess.TimezoneConfigureTest
      - name: Test charEncoding
        run: mvn clean test -Dtest=\
          com.jd.jdbc.engine.CharEncodingTest
